#define SMALL_INDIVID 	-1
#define DIFFERENT_SIZE 	-2
#define SUCCESSFUL 		 1
#define UNSUCCESSFUL 	 0

#define INDIVIDS_EQUAL 	 1
#define INDIVIDS_UNEQUAL 0
	
#define CHECK_HEIGHT 0
#define CHECK_RADIUS 1

#define ROTNEST_DEFAULT 0
#define ROTNEST_MORE	1
#define ROTNEST_FULL 	2
#define MTXNEST_DEFAULT 0
#define MTXNEST_FULL	1
